<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Журнал здоров'я: таблиця health_event (тиск/пульс, болі, ліки, нотатки).
 * Структуровані поля типу — у JSONB payload.
 */
final class Version20260823214649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'health_event: універсальні події здоров\'я з JSONB payload';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE health_event (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            family_member_id INT NOT NULL,
            date DATE NOT NULL,
            time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
            type VARCHAR(40) NOT NULL,
            payload JSONB NOT NULL,
            note TEXT DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_health_event_date ON health_event (date)');
        $this->addSql('CREATE INDEX IDX_606D216DBC594993 ON health_event (family_member_id)');
        $this->addSql('ALTER TABLE health_event ADD CONSTRAINT FK_606D216DBC594993
            FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE health_event');
    }
}
