<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Вага переїжджає в журнал здоров'я: weight_entry → health_event (type='weight',
 * payload {"kg": …}), окрема таблиця видаляється.
 */
final class Version20260824204317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'weight_entry → health_event (type=weight), DROP weight_entry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("INSERT INTO health_event (family_member_id, date, time, type, payload, note)
            SELECT family_member_id, date, NULL, 'weight', jsonb_build_object('kg', weight_kg), NULL
            FROM weight_entry");
        $this->addSql('DROP TABLE weight_entry');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE weight_entry (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            family_member_id INT NOT NULL,
            date DATE NOT NULL,
            weight_kg DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_member_date ON weight_entry (family_member_id, date)');
        $this->addSql('ALTER TABLE weight_entry ADD CONSTRAINT FK_weight_member
            FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("INSERT INTO weight_entry (family_member_id, date, weight_kg)
            SELECT family_member_id, date, (payload->>'kg')::double precision
            FROM health_event WHERE type = 'weight'");
        $this->addSql("DELETE FROM health_event WHERE type = 'weight'");
    }
}
