<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Шаблони днів меню: day_template + day_template_item (знімок дня на всю сім'ю). */
final class Version20260901161650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Шаблони днів меню (day_template, day_template_item)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE day_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_day_template_name ON day_template (name)');
        $this->addSql('CREATE TABLE day_template_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slot VARCHAR(20) NOT NULL, amount DOUBLE PRECISION DEFAULT NULL, template_id INT NOT NULL, family_member_id INT NOT NULL, dish_id INT DEFAULT NULL, ingredient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A3B66335DA0FB8 ON day_template_item (template_id)');
        $this->addSql('CREATE INDEX IDX_9A3B6633BC594993 ON day_template_item (family_member_id)');
        $this->addSql('CREATE INDEX IDX_9A3B6633148EB0CB ON day_template_item (dish_id)');
        $this->addSql('CREATE INDEX IDX_9A3B6633933FE08C ON day_template_item (ingredient_id)');
        $this->addSql('ALTER TABLE day_template_item ADD CONSTRAINT FK_9A3B66335DA0FB8 FOREIGN KEY (template_id) REFERENCES day_template (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE day_template_item ADD CONSTRAINT FK_9A3B6633BC594993 FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE day_template_item ADD CONSTRAINT FK_9A3B6633148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE day_template_item ADD CONSTRAINT FK_9A3B6633933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE day_template_item DROP CONSTRAINT FK_9A3B66335DA0FB8');
        $this->addSql('ALTER TABLE day_template_item DROP CONSTRAINT FK_9A3B6633BC594993');
        $this->addSql('ALTER TABLE day_template_item DROP CONSTRAINT FK_9A3B6633148EB0CB');
        $this->addSql('ALTER TABLE day_template_item DROP CONSTRAINT FK_9A3B6633933FE08C');
        $this->addSql('DROP TABLE day_template');
        $this->addSql('DROP TABLE day_template_item');
    }
}
