<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802175048 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dish (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) DEFAULT NULL, name VARCHAR(200) NOT NULL, category VARCHAR(20) NOT NULL, recipe TEXT DEFAULT NULL, youtube_url VARCHAR(255) DEFAULT NULL, batch_cooking BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_957D8CB877153098 ON dish (code)');
        $this->addSql('CREATE TABLE dish_portion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dish_id INT NOT NULL, family_member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7037E7B0148EB0CB ON dish_portion (dish_id)');
        $this->addSql('CREATE INDEX IDX_7037E7B0BC594993 ON dish_portion (family_member_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_dish_member ON dish_portion (dish_id, family_member_id)');
        $this->addSql('CREATE TABLE dish_portion_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, portion_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6451DC08162BE352 ON dish_portion_ingredient (portion_id)');
        $this->addSql('CREATE INDEX IDX_6451DC08933FE08C ON dish_portion_ingredient (ingredient_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_portion_ingredient ON dish_portion_ingredient (portion_id, ingredient_id)');
        $this->addSql('CREATE TABLE family_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, kcal_target INT NOT NULL, protein_target INT DEFAULT NULL, fat_target INT DEFAULT NULL, carbs_target INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9D4AD6D5E237E06 ON family_member (name)');
        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, category VARCHAR(30) NOT NULL, unit VARCHAR(10) NOT NULL, kcal_per100 DOUBLE PRECISION NOT NULL, protein_per100 DOUBLE PRECISION NOT NULL, fat_per100 DOUBLE PRECISION NOT NULL, carbs_per100 DOUBLE PRECISION NOT NULL, piece_weight_grams DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BAF78705E237E06 ON ingredient (name)');
        $this->addSql('CREATE TABLE meal_plan_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, slot VARCHAR(20) NOT NULL, family_member_id INT NOT NULL, dish_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EFEB6E06BC594993 ON meal_plan_entry (family_member_id)');
        $this->addSql('CREATE INDEX IDX_EFEB6E06148EB0CB ON meal_plan_entry (dish_id)');
        $this->addSql('CREATE INDEX idx_meal_plan_date ON meal_plan_entry (date)');
        $this->addSql('CREATE TABLE weight_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, weight_kg DOUBLE PRECISION NOT NULL, family_member_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1486C8C0BC594993 ON weight_entry (family_member_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_member_date ON weight_entry (family_member_id, date)');
        $this->addSql('ALTER TABLE dish_portion ADD CONSTRAINT FK_7037E7B0148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish_portion ADD CONSTRAINT FK_7037E7B0BC594993 FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish_portion_ingredient ADD CONSTRAINT FK_6451DC08162BE352 FOREIGN KEY (portion_id) REFERENCES dish_portion (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish_portion_ingredient ADD CONSTRAINT FK_6451DC08933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry ADD CONSTRAINT FK_EFEB6E06BC594993 FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan_entry ADD CONSTRAINT FK_EFEB6E06148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE weight_entry ADD CONSTRAINT FK_1486C8C0BC594993 FOREIGN KEY (family_member_id) REFERENCES family_member (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dish_portion DROP CONSTRAINT FK_7037E7B0148EB0CB');
        $this->addSql('ALTER TABLE dish_portion DROP CONSTRAINT FK_7037E7B0BC594993');
        $this->addSql('ALTER TABLE dish_portion_ingredient DROP CONSTRAINT FK_6451DC08162BE352');
        $this->addSql('ALTER TABLE dish_portion_ingredient DROP CONSTRAINT FK_6451DC08933FE08C');
        $this->addSql('ALTER TABLE meal_plan_entry DROP CONSTRAINT FK_EFEB6E06BC594993');
        $this->addSql('ALTER TABLE meal_plan_entry DROP CONSTRAINT FK_EFEB6E06148EB0CB');
        $this->addSql('ALTER TABLE weight_entry DROP CONSTRAINT FK_1486C8C0BC594993');
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE dish_portion');
        $this->addSql('DROP TABLE dish_portion_ingredient');
        $this->addSql('DROP TABLE family_member');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE meal_plan_entry');
        $this->addSql('DROP TABLE weight_entry');
    }
}
